nvm install 10
nvm use 10
npm install discord.js
npm install ytdl-core
npm i opusscript
npm install get-youtube-id
npm install youtube-info
npm install simple-youtube-api
npm install queue
npm install ffmpeg-binaries 
npm install node-opus
npm install opusscript
npm i discord.js-musicbot-addon
npm install opusscript 
npm i ffmpeg-binarie
